services:
    home-inventory:
        build:
            context: .
        container_name: inventory-app
        volumes:
            - .:/app
        networks:
            - shared
        command: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --workers=1 --max-requests=1
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.inventory.rule=Host(`inventory.test`)
            - traefik.http.routers.inventory.entrypoints=web
            - traefik.http.services.inventory.loadbalancer.server.port=8000

networks:
    shared:
        external: true
