// Generates resources/icons/lucide.php from the lucide-static npm package:
// a name => [s => inner svg markup, t => search keywords] map that
// App\Support\IconLibrary loads once per Octane worker. Re-run with
// `npm run build:icons` after updating lucide-static.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconsDir = join(root, 'node_modules', 'lucide-static', 'icons');
const outFile = join(root, 'resources', 'icons', 'lucide.php');

let tags = {};
try {
    tags = JSON.parse(readFileSync(join(root, 'node_modules', 'lucide-static', 'tags.json'), 'utf8'));
} catch {
    console.warn('tags.json not found — icons will be searchable by name only.');
}

const phpQuote = (value) => `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;

const entries = [];

for (const file of readdirSync(iconsDir).sort()) {
    if (!file.endsWith('.svg')) continue;

    const name = file.slice(0, -4);
    const svg = readFileSync(join(iconsDir, file), 'utf8');
    const match = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);

    if (!match) {
        console.warn(`skipped ${file}: no <svg> element found`);
        continue;
    }

    const inner = match[1].replace(/\s+/g, ' ').trim();
    const keywords = (tags[name] ?? []).join(' ');

    entries.push(`    ${phpQuote(name)} => ['s' => ${phpQuote(inner)}, 't' => ${phpQuote(keywords)}],`);
}

const php = `<?php

// GENERATED by scripts/build-icons.mjs from lucide-static (ISC license) — do not edit by hand.

return [
${entries.join('\n')}
];
`;

writeFileSync(outFile, php);
console.log(`${entries.length} icons written to ${outFile}`);
